wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      4: 3.7.7
      5: 0.10.22
      8:
      - 5
batch_size:
  desc: null
  value: 256
block_size:
  desc: null
  value: 5
epochs:
  desc: null
  value: 1001
lr:
  desc: null
  value: 0.005
points_per_sample:
  desc: null
  value: 2000
