wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      4: 3.7.7
      5: 0.10.31
      8:
      - 5
act_norm:
  desc: null
  value: true
batch_size:
  desc: null
  value: 256
block_size:
  desc: null
  value: 5
epochs:
  desc: null
  value: 31
lr:
  desc: null
  value: 0.005
net:
  desc: null
  value: MLP
non_linearity:
  desc: null
  value: prelu
permuter:
  desc: null
  value: LinearLU
points_per_sample:
  desc: null
  value: 30000
wt_c_l:
  desc: null
  value: 1
wt_f_l:
  desc: null
  value: 2
wt_mmd_l:
  desc: null
  value: 0.1
